// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloStream.proto

package com.grpc.demo.proto.hellostream;

public final class HelloStreamProto {
  private HelloStreamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hellostream_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hellostream_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hellostream_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hellostream_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hellostream_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hellostream_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hellostream_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hellostream_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hellostream_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hellostream_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021helloStream.proto\022\013hellostream\"\032\n\014Hell" +
      "oRequest\022\n\n\002no\030\001 \001(\t\":\n\017StudentResponse\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t" +
      "\"L\n\023StudentResponseList\0225\n\017studentRespon" +
      "se\030\001 \003(\0132\034.hellostream.StudentResponse\"%" +
      "\n\rStreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n" +
      "\016StreamResponse\022\025\n\rresponse_info\030\001 \001(\t2\370" +
      "\001\n\013ExampleGrpc\022M\n\016getListMessage\022\031.hello" +
      "stream.HelloRequest\032\034.hellostream.Studen" +
      "tResponse\"\0000\001\022Q\n\016getStudentList\022\031.hellos" +
      "tream.HelloRequest\032 .hellostream.Student" +
      "ResponseList\"\000(\001\022G\n\006BiTalk\022\032.hellostream" +
      ".StreamRequest\032\033.hellostream.StreamRespo" +
      "nse\"\000(\0010\001B5\n\037com.grpc.demo.proto.hellost" +
      "reamB\020HelloStreamProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hellostream_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hellostream_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hellostream_HelloRequest_descriptor,
        new java.lang.String[] { "No", });
    internal_static_hellostream_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hellostream_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hellostream_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_hellostream_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hellostream_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hellostream_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_hellostream_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hellostream_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hellostream_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_hellostream_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_hellostream_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hellostream_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
