// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloStream.proto

package com.grpc.demo.proto.hellostream;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hellostream.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string no = 1;</code>
   */
  java.lang.String getNo();
  /**
   * <code>string no = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoBytes();
}
