// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloStream.proto

package com.grpc.demo.proto.hellostream;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hellostream.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .hellostream.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.grpc.demo.proto.hellostream.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .hellostream.StudentResponse studentResponse = 1;</code>
   */
  com.grpc.demo.proto.hellostream.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .hellostream.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .hellostream.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.grpc.demo.proto.hellostream.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .hellostream.StudentResponse studentResponse = 1;</code>
   */
  com.grpc.demo.proto.hellostream.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
